### Goldsmiths University of London
### Author....: Carlos Manuel de Oliveira Alves
### Student...: cdeol003
### Created...: 11/02/2023
### FYP.......: NeuroCredit

In [1]:
# Import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Import the dataset
dataset = pd.read_csv('data.csv')

# Split the dataset into independent and dependent variables

# Select all the columns except the last one as the independent variables vector
X = dataset.iloc[:, :-1].values

# Select the last column as the dependent variable vector
y = dataset.iloc[:, -1].values

In [3]:
# Print first 5 rows with the independent variables vector
print(X[:5])

[['Poor' 'Self-Employed' 'None' 'Fair' 'Auto' 'Judgement'
  'Debt Consolidation' 30971 11969 78 21 0 5 0 135 18627 25 4648 4719]
 ['Poor' 'Unemployed' 'Investment' 'Excellent' 'Mortgage' 'Collection'
  'Home Improvement' 19120 45396 81 92 0 2 1 19857 11996 58 2657 19366]
 ['Excellent' 'Unemployed' 'House' 'Poor' 'Other' 'Bankruptcy'
  'Debt Consolidation' 48687 18880 73 27 0 3 1 17501 18074 30 2487 15500]
 ['Fair' 'Unemployed' 'Car' 'Good' 'Other' 'Tax Lien' 'Home Improvement'
  40997 11527 6 19 3 3 4 9376 5073 60 3100 12380]
 ['Good' 'Unemployed' 'House' 'Excellent' 'Personal' 'None' 'Business'
  35485 27016 33 49 5 2 3 18960 14542 99 1596 7946]]


In [4]:
# Print first 5 rows with the dependent variable vector
print(y[:5])

['Rejected' 'Rejected' 'Rejected' 'Rejected' 'Rejected']


In [5]:
# Print the missing values in the dataset
print(dataset.isnull().sum())

credit_history                                     0
employment_status                                  0
collateral                                         0
payment_history                                    0
type_of_credit_accounts                            0
public_records_and_collections                     0
purpose_of_loan                                    0
income                                             0
assets_value                                       0
debt_to_income_ratio                               0
length_of_credit_history                           0
number_of_credit_inquiries                         0
number_of_credit_accounts                          0
number_of_credit_accounts_opened_last_12_months    0
current_balance_of_credit_accounts                 0
total_credit_limit                                 0
total_credit_utilization                           0
loan_amount                                        0
saving_account_balance                        

In [6]:
# Encode the categorical data

# Import the library for encoding the categorical data
from sklearn.compose import ColumnTransformer

# Import the library for one hot encoding the categorical data
from sklearn.preprocessing import OneHotEncoder

# Create an object of the ColumnTransformer class
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1,2,3,4,5,6])], remainder='passthrough')

# Encoding the independent variables vector
X = np.array(ct.fit_transform(X))

In [7]:
# Print first 5 rows with the independent variables vector
print(X[:5])

[[0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0
  0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 30971 11969
  78 21 0 5 0 135 18627 25 4648 4719]
 [0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 19120 45396
  81 92 0 2 1 19857 11996 58 2657 19366]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 48687 18880
  73 27 0 3 1 17501 18074 30 2487 15500]
 [0.0 1.0 0.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 40997 11527
  6 19 3 3 4 9376 5073 60 3100 12380]
 [0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 35485 27016
  33 49 5 2 3 18960 14542 99 1596 7946]]


In [10]:
# Encoding the dependent variable vector

# Import the library for encoding the categorical data
from sklearn.preprocessing import LabelEncoder

# Create an object of the LabelEncoder class
le = LabelEncoder()

# Encoding the dependent variable vector
y = le.fit_transform(y)

In [11]:
# Print first 5 rows with the dependent variable vector after encoding
print(y[:5])

[1 1 1 1 1]


In [12]:
# Split the dataset into training and test sets

# Import the library for splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [13]:
# Print first 5 rows from the X training set
print(X_train[:5])

[[0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 36933 32921
  12 23 5 2 1 12728 4417 33 1673 17013]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 42898 41738
  50 21 3 5 0 10581 1886 7 4918 5022]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 12434 31547
  32 80 0 3 2 11553 16452 33 3848 6464]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 18089 18164
  78 44 1 3 5 4784 12920 59 1886 7582]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 1.0
  0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 15341 47687
  87 62 2 0 3 11877 1632 22 2821 11378]]


In [14]:
# Print first 5 rows from the X test set
print(X_test[:5])

[[0.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 14670 28260
  79 29 4 2 0 13341 1874 22 2942 6405]
 [0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0
  0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 20346 20062
  90 21 1 5 0 19669 2938 59 2848 9107]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 46322 40877
  60 94 4 3 4 1829 2499 0 3514 3353]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 41282 13191
  38 54 5 3 3 15807 5887 92 3152 19206]
 [0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 22875 19554
  38 83 2 2 5 12738 8179 52 2228 17945]]


In [15]:
# Print first 5 rows from the Y training set
print(y_train[:5])

[1 1 0 1 1]


In [16]:
# Print first 5 rows from the Y test set
print(y_test[:5])

[0 1 1 1 1]


In [17]:
# Feature scaling

# Import the library for feature scaling
from sklearn.preprocessing import StandardScaler

# Create an instance of the StandardScaler class
sc = StandardScaler()

# Fit the training set using the numerical columns
X_train[:, 33:] = sc.fit_transform(X_train[:, 33:])

# Transform the test set using the numerical columns
X_test[:, 33:] = sc.transform(X_test[:, 33:])

In [18]:
# Print first 3 rows from the X training set
print(X_train[:3])

[[0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.5870100043393323 0.2917414330328959 -1.3361545310763985
  -0.8821090336865706 1.4910225551575205 -0.2917745192078006
  -0.8045195835759038 0.4780163302018978 -0.9447594247583616
  -0.5632067010101276 -1.13876683459393 1.2023332733261243]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0
  1.0922807178278127 1.0428648809425443 -0.011417144580980268
  -0.9510776837011578 0.3187198090877256 1.5083767561102492
  -1.3817533655137721 0.09861672734800296 -1.379386590397935
  -1.4805676548872344 1.6206122456678749 -0.8887099264008494]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0
  -1.4881999218558537 0.17468987156892216 -0.6389243276577573
  1.0834974917291653 -1.4397343100169668 0.

In [19]:
# Print first 3 rows from the X test set
print(X_test[:3])

[[0.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  -1.2987975219631056 -0.10533085807596997 0.9995666503760494
  -0.6752030836428089 0.9048711821226231 -0.2917745192078006
  -1.3817533655137721 0.586340483229116 -1.381447248630916
  -0.9513209507273651 -0.059675292882919014 -0.6475363174255843]
 [0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0
  0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  -0.8180068145430527 -0.8037214700713535 1.383043262256302
  -0.9510776837011578 -0.8535829369820693 1.5083767561102492
  -1.3817533655137721 1.7045708916405957 -1.1987355519732683
  0.35415425286697927 -0.13960799967632723 -0.17634970032423464]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  1.3823137309015021 0.969515976706386 0.33719795712834033
  1.5662780418312758 0.9048711821226231

In [22]:
# Print all rows from the Y test set
print(y_test)

[0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 0
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1
 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1
 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1]


In [23]:
# Train the Logistic Regression model on the training set

# Import the library for training the Logistic Regression model
from sklearn.linear_model import LogisticRegression

# Create an instance of the LogisticRegression class
classifier = LogisticRegression(random_state = 0)

# Train the Logistic Regression model on the training set
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [1]:
# Import the library for encoding the categorical data
from sklearn.preprocessing import OneHotEncoder

# Define the data to be encoded
cat_d = ['Poor','Self-Employed','None','Fair','Auto','Judgement','Debt Consolidation']

# Create the one-hot encoder object
encoder = OneHotEncoder()

# Fit the encoder to the data
encoder.fit([[x] for x in cat_d])

# Transform the data into a one-hot encoded matrix
cat_d_encoded = encoder.transform([[x] for x in cat_d]).toarray()

# Print the resulting matrix
print(cat_d_encoded)


[[0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]


In [31]:
# Input the new data to predict the result

# Declare a new data point with categorical data
cat_d = ['Poor','Self-Employed','None','Fair','Auto','Judgement','Debt Consolidation']

# Transform the categorical data into numerical data
cat_d = np.array(ct.transform([cat_d]))

# Encode the categorical data
cat_d = np.array([[cat_d]])

# Declare a new data point with numerical data
num_d = [30971,11969,78,21,0,5,0,135,18627,25,4648,4719]

# Combine the categorical and numerical data
new_d = cat_d + num_d


ValueError: X has 7 features, but ColumnTransformer is expecting 19 features as input.

In [27]:
# Predict a new result

classifier.predict([[new_d]])

ValueError: dtype='numeric' is not compatible with arrays of bytes/strings.Convert your data to numeric values explicitly instead.