### Goldsmiths University of London
### Author....: Carlos Manuel de Oliveira Alves
### Student...: cdeol003
### Created...: 11/02/2023
### FYP.......: NeuroCredit

In [1]:
# Import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Import the dataset
dataset = pd.read_csv('data.csv')

# Split the dataset into independent and dependent variables

# Select all the columns except the last one as the independent variables vector
X = dataset.iloc[:, :-1].values

# Select the last column as the dependent variable vector
y = dataset.iloc[:, -1].values

In [6]:
# Print first 5 rows with the independent variables vector
print(X[:5])

[['Fair' 34084 'Employed' 'Land' 39837 76 'Excellent' 84 5 0 3 'Auto'
  12377 6149 80 'Judgement' 4641 'Car Financing' 3011]
 ['Good' 20938 'Self-Employed' 'Car' 33241 53 'Poor' 59 3 3 0 'Auto' 1430
  18922 33 'Judgement' 3592 'Other' 16448]
 ['Good' 20734 'Employed' 'Land' 12926 52 'Excellent' 84 1 1 3 'Auto'
  16049 1197 57 'Other' 1955 'Other' 6192]
 ['Good' 14186 'Unemployed' 'Car' 16586 67 'Poor' 92 5 5 0 'Student' 4938
  13206 92 'Collection' 3652 'Home Improvement' 7279]
 ['Excellent' 46693 'Unemployed' 'Land' 30771 66 'Excellent' 39 1 2 4
  'Mortgage' 10459 4011 50 'Collection' 2544 'Home Improvement' 7619]]


In [7]:
# Print first 5 rows with the dependent variable vector
print(y[:5])

['Rejected' 'Approved' 'Rejected' 'Rejected' 'Rejected']


In [8]:
# Print the missing values in the dataset
print(dataset.isnull().sum())

credit_history                                     0
income                                             0
employment_status                                  0
collateral                                         0
assets_value                                       0
debt_to_income_ratio                               0
payment_history                                    0
length_of_credit_history                           0
number_of_credit_inquiries                         0
number_of_credit_accounts                          0
number_of_credit_accounts_opened_last_12_months    0
type_of_credit_accounts                            0
current_balance_of_credit_accounts                 0
total_credit_limit                                 0
total_credit_utilization                           0
public_records_and_collections                     0
loan_amount                                        0
purpose_of_loan                                    0
saving_account_balance                        

In [16]:
# Encode the categorical data

# Import the library for encoding the categorical data
from sklearn.compose import ColumnTransformer

# Import the library for one hot encoding the categorical data
from sklearn.preprocessing import OneHotEncoder

# Create an object of the ColumnTransformer class
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,2,3,6,11,15,17])], remainder='passthrough')

# Encoding the independent variables vector
X = np.array(ct.fit_transform(X))


In [17]:
# Print first 5 rows with the independent variables vector
print(X[:5])

[[0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0
  0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 34084 39837
  76 84 5 0 3 12377 6149 80 4641 3011]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0
  0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 20938 33241
  53 59 3 3 0 1430 18922 33 3592 16448]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0
  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 20734 12926
  52 84 1 1 3 16049 1197 57 1955 6192]
 [0.0 0.0 1.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 14186 16586
  67 92 5 5 0 4938 13206 92 3652 7279]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 46693 30771
  66 39 1 2 4 10459 4011 50 2544 7619]]


In [15]:
# Print all the index numbers of the categorical columns
print(dataset.columns.get_loc("credit_history"))
print(dataset.columns.get_loc("employment_status"))
print(dataset.columns.get_loc("collateral"))
print(dataset.columns.get_loc("payment_history"))
print(dataset.columns.get_loc("type_of_credit_accounts"))
print(dataset.columns.get_loc("public_records_and_collections"))
print(dataset.columns.get_loc("purpose_of_loan"))
print(dataset.columns.get_loc("approval_status"))

0
2
3
6
11
15
17
19


In [12]:
# Print all the categorical columns in the dataset
print(dataset.select_dtypes(include=['object']).columns)

Index(['credit_history', 'employment_status', 'collateral', 'payment_history',
       'type_of_credit_accounts', 'public_records_and_collections',
       'purpose_of_loan', 'approval_status'],
      dtype='object')


In [18]:
# Encoding the dependent variable vector

# Import the library for encoding the categorical data
from sklearn.preprocessing import LabelEncoder

# Create an object of the LabelEncoder class
le = LabelEncoder()

# Encoding the dependent variable vector
y = le.fit_transform(y)

In [19]:
# Print first 5 rows with the dependent variable vector after encoding
print(y[:5])

[1 0 1 1 1]


In [27]:
# Split the dataset into training and test sets

# Import the library for splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [28]:
# Print first 5 rows from the X training set
print(X_train[:5])

[[0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 44095 45322
  4 72 0 0 1 10523 10319 23 4164 943]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0
  0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 39334 22635
  28 26 2 1 5 19932 12131 38 2763 5416]
 [0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 10662 13058
  7 43 0 2 5 2624 9282 56 2961 520]
 [0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 19322 32150
  58 39 4 4 4 18427 17984 44 2147 17063]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 12846 15433
  60 90 4 5 2 7590 2352 82 2878 2498]]


In [29]:
# Print first 5 rows from the X test set
print(X_test[:5])

[[0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0
  1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 15690 37324
  43 95 3 0 5 3518 2645 56 3491 19806]
 [0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 29904 25923
  74 19 3 0 0 4056 2757 13 2927 17448]
 [0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0
  0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 23057 28818
  47 22 0 3 5 13999 19216 70 3604 403]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 31309 45555
  99 68 4 5 5 18232 7657 82 1987 3038]
 [0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 12429 31004
  86 96 1 2 5 16760 17365 93 4173 14253]]


In [30]:
# Print first 5 rows from the Y training set
print(y_train[:5])

[1 1 1 1 1]


In [32]:
# Print first 5 rows from the Y test set
print(y_test[:5])

[1 1 1 1 0]
