### Goldsmiths University of London
### Author....: Carlos Manuel de Oliveira Alves
### Student...: cdeol003
### Created...: 11/02/2023
### FYP.......: NeuroCredit

In [1]:
# Import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Import the dataset
dataset = pd.read_csv('data.csv')

# Split the dataset into independent and dependent variables

# Select all the columns except the last one as the independent variables vector
X = dataset.iloc[:, :-1].values

# Select the last column as the dependent variable vector
y = dataset.iloc[:, -1].values

In [3]:
# Print first 5 rows with the independent variables vector
print(X[:5])

[['Poor' 'Self-Employed' 'None' 'Fair' 'Auto' 'Judgement'
  'Debt Consolidation' 30971 11969 78 21 0 5 0 135 18627 25 4648 4719]
 ['Poor' 'Unemployed' 'Investment' 'Excellent' 'Mortgage' 'Collection'
  'Home Improvement' 19120 45396 81 92 0 2 1 19857 11996 58 2657 19366]
 ['Excellent' 'Unemployed' 'House' 'Poor' 'Other' 'Bankruptcy'
  'Debt Consolidation' 48687 18880 73 27 0 3 1 17501 18074 30 2487 15500]
 ['Fair' 'Unemployed' 'Car' 'Good' 'Other' 'Tax Lien' 'Home Improvement'
  40997 11527 6 19 3 3 4 9376 5073 60 3100 12380]
 ['Good' 'Unemployed' 'House' 'Excellent' 'Personal' 'None' 'Business'
  35485 27016 33 49 5 2 3 18960 14542 99 1596 7946]]


In [4]:
# Print first 5 rows with the dependent variable vector
print(y[:5])

['Rejected' 'Rejected' 'Rejected' 'Rejected' 'Rejected']


In [5]:
# Print the missing values in the dataset
print(dataset.isnull().sum())

credit_history                                     0
employment_status                                  0
collateral                                         0
payment_history                                    0
type_of_credit_accounts                            0
public_records_and_collections                     0
purpose_of_loan                                    0
income                                             0
assets_value                                       0
debt_to_income_ratio                               0
length_of_credit_history                           0
number_of_credit_inquiries                         0
number_of_credit_accounts                          0
number_of_credit_accounts_opened_last_12_months    0
current_balance_of_credit_accounts                 0
total_credit_limit                                 0
total_credit_utilization                           0
loan_amount                                        0
saving_account_balance                        

In [7]:
# Encode the categorical data

# Import the library for encoding the categorical data
from sklearn.compose import ColumnTransformer

# Import the library for one hot encoding the categorical data
from sklearn.preprocessing import OneHotEncoder

# Create an object of the ColumnTransformer class
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1,2,3,4,5,6])], remainder='passthrough')

# Encoding the independent variables vector
X = np.array(ct.fit_transform(X))


In [8]:
# Print first 5 rows with the independent variables vector
print(X[:5])

[[0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0
  0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 30971 11969
  78 21 0 5 0 135 18627 25 4648 4719]
 [0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 19120 45396
  81 92 0 2 1 19857 11996 58 2657 19366]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 48687 18880
  73 27 0 3 1 17501 18074 30 2487 15500]
 [0.0 1.0 0.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 40997 11527
  6 19 3 3 4 9376 5073 60 3100 12380]
 [0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 35485 27016
  33 49 5 2 3 18960 14542 99 1596 7946]]


In [6]:
# Print all the index numbers of the categorical columns
print(dataset.columns.get_loc("credit_history"))
print(dataset.columns.get_loc("employment_status"))
print(dataset.columns.get_loc("collateral"))
print(dataset.columns.get_loc("payment_history"))
print(dataset.columns.get_loc("type_of_credit_accounts"))
print(dataset.columns.get_loc("public_records_and_collections"))
print(dataset.columns.get_loc("purpose_of_loan"))
print(dataset.columns.get_loc("approval_status"))

0
1
2
3
4
5
6
19


In [9]:
# Print all the categorical columns in the dataset
print(dataset.select_dtypes(include=['object']).columns)

Index(['credit_history', 'employment_status', 'collateral', 'payment_history',
       'type_of_credit_accounts', 'public_records_and_collections',
       'purpose_of_loan', 'approval_status'],
      dtype='object')


In [10]:
# Encoding the dependent variable vector

# Import the library for encoding the categorical data
from sklearn.preprocessing import LabelEncoder

# Create an object of the LabelEncoder class
le = LabelEncoder()

# Encoding the dependent variable vector
y = le.fit_transform(y)

In [11]:
# Print first 5 rows with the dependent variable vector after encoding
print(y[:5])

[1 1 1 1 1]


In [12]:
# Split the dataset into training and test sets

# Import the library for splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [13]:
# Print first 5 rows from the X training set
print(X_train[:5])

[[0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 36933 32921
  12 23 5 2 1 12728 4417 33 1673 17013]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 42898 41738
  50 21 3 5 0 10581 1886 7 4918 5022]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 12434 31547
  32 80 0 3 2 11553 16452 33 3848 6464]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 18089 18164
  78 44 1 3 5 4784 12920 59 1886 7582]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 1.0
  0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 15341 47687
  87 62 2 0 3 11877 1632 22 2821 11378]]


In [14]:
# Print first 5 rows from the X test set
print(X_test[:5])

[[0.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 14670 28260
  79 29 4 2 0 13341 1874 22 2942 6405]
 [0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0
  0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 20346 20062
  90 21 1 5 0 19669 2938 59 2848 9107]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 46322 40877
  60 94 4 3 4 1829 2499 0 3514 3353]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 41282 13191
  38 54 5 3 3 15807 5887 92 3152 19206]
 [0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 22875 19554
  38 83 2 2 5 12738 8179 52 2228 17945]]


In [15]:
# Print first 5 rows from the Y training set
print(y_train[:5])

[1 1 0 1 1]


In [16]:
# Print first 5 rows from the Y test set
print(y_test[:5])

[0 1 1 1 1]


In [20]:

# Feature scaling

# Import the library for feature scaling
from sklearn.preprocessing import StandardScaler

# Create an instance of the StandardScaler class
sc = StandardScaler()

# Fit the training set using the numerical columns
X_train[:, 33:] = sc.fit_transform(X_train[:, 33:])

# Transform the test set using the numerical columns
X_test[:, 33:] = sc.transform(X_test[:, 33:])

In [22]:
# Print first 3 rows from the X training set
print(X_train[:3])

[[0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.5870100043393324 0.291741433032896 -1.3361545310763985
  -0.882109033686571 1.4910225551575225 -0.29177451920780106
  -0.804519583575905 0.47801633020189765 -0.9447594247583623
  -0.5632067010101276 -1.1387668345939297 1.2023332733261243]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0
  1.092280717827813 1.042864880942545 -0.011417144580980301
  -0.9510776837011583 0.318719809087726 1.5083767561102517
  -1.3817533655137744 0.09861672734800296 -1.3793865903979357
  -1.4805676548872344 1.620612245667874 -0.8887099264008494]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0
  -1.4881999218558541 0.17468987156892218 -0.6389243276577573
  1.083497491729166 -1.4397343100169693 0.308

In [23]:
# Print first 3 rows from the X test set
print(X_test[:3])

[[0.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  -1.298797521963106 -0.10533085807597008 0.9995666503760494
  -0.6752030836428092 0.9048711821226244 -0.29177451920780106
  -1.3817533655137744 0.5863404832291158 -1.3814472486309166
  -0.9513209507273651 -0.059675292882919166 -0.6475363174255843]
 [0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0
  0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  -0.818006814543053 -0.803721470071354 1.383043262256302
  -0.9510776837011583 -0.8535829369820708 1.5083767561102517
  -1.3817533655137744 1.704570891640595 -1.198735551973269
  0.3541542528669792 -0.13960799967632734 -0.17634970032423458]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  1.3823137309015026 0.9695159767063866 0.3371979571283403
  1.5662780418312767 0.9048711821226244 0.

In [24]:
# Simple Linear Regression

# Import the libraries to implement the linear regression model
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd

In [25]:
# Import the dataset to implement the linear regression model
dataset = pd.read_csv('data.csv')

# Select all the columns except the last one as the independent variables vector
X = dataset.iloc[:, :-1].values

# Select the last column as the dependent variable vector
y = dataset.iloc[:, -1].values

In [ ]:
# Split the dataset into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)