### Goldsmiths University of London
### Author....: Carlos Manuel de Oliveira Alves
### Student...: cdeol003
### Created...: 11/02/2023
### FYP.......: NeuroCredit

In [1]:
# Import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Import the dataset
dataset = pd.read_csv('data.csv')

# Split the dataset into independent and dependent variables

# Select all the columns except the last one as the independent variables vector
X = dataset.iloc[:, :-1].values

# Select the last column as the dependent variable vector
y = dataset.iloc[:, -1].values

In [3]:
# Print first 5 rows with the independent variables vector
print(X[:5])

[['Poor' 'Self-Employed' 'None' 'Fair' 'Auto' 'Judgement'
  'Debt Consolidation' 30971 11969 78 21 0 5 0 135 18627 25 4648 4719]
 ['Poor' 'Unemployed' 'Investment' 'Excellent' 'Mortgage' 'Collection'
  'Home Improvement' 19120 45396 81 92 0 2 1 19857 11996 58 2657 19366]
 ['Excellent' 'Unemployed' 'House' 'Poor' 'Other' 'Bankruptcy'
  'Debt Consolidation' 48687 18880 73 27 0 3 1 17501 18074 30 2487 15500]
 ['Fair' 'Unemployed' 'Car' 'Good' 'Other' 'Tax Lien' 'Home Improvement'
  40997 11527 6 19 3 3 4 9376 5073 60 3100 12380]
 ['Good' 'Unemployed' 'House' 'Excellent' 'Personal' 'None' 'Business'
  35485 27016 33 49 5 2 3 18960 14542 99 1596 7946]]


In [4]:
# Print first 5 rows with the dependent variable vector
print(y[:5])

['Rejected' 'Rejected' 'Rejected' 'Rejected' 'Rejected']


In [5]:
# Print the missing values in the dataset
print(dataset.isnull().sum())

credit_history                                     0
employment_status                                  0
collateral                                         0
payment_history                                    0
type_of_credit_accounts                            0
public_records_and_collections                     0
purpose_of_loan                                    0
income                                             0
assets_value                                       0
debt_to_income_ratio                               0
length_of_credit_history                           0
number_of_credit_inquiries                         0
number_of_credit_accounts                          0
number_of_credit_accounts_opened_last_12_months    0
current_balance_of_credit_accounts                 0
total_credit_limit                                 0
total_credit_utilization                           0
loan_amount                                        0
saving_account_balance                        

In [7]:
# Encode the categorical data

# Import the library for encoding the categorical data
from sklearn.compose import ColumnTransformer

# Import the library for one hot encoding the categorical data
from sklearn.preprocessing import OneHotEncoder

# Create an object of the ColumnTransformer class
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1,2,3,4,5,6])], remainder='passthrough')

# Encoding the independent variables vector
X = np.array(ct.fit_transform(X))


In [8]:
# Print first 5 rows with the independent variables vector
print(X[:5])

[[0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0
  0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 30971 11969
  78 21 0 5 0 135 18627 25 4648 4719]
 [0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 19120 45396
  81 92 0 2 1 19857 11996 58 2657 19366]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 48687 18880
  73 27 0 3 1 17501 18074 30 2487 15500]
 [0.0 1.0 0.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 40997 11527
  6 19 3 3 4 9376 5073 60 3100 12380]
 [0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 35485 27016
  33 49 5 2 3 18960 14542 99 1596 7946]]


In [6]:
# Print all the index numbers of the categorical columns
print(dataset.columns.get_loc("credit_history"))
print(dataset.columns.get_loc("employment_status"))
print(dataset.columns.get_loc("collateral"))
print(dataset.columns.get_loc("payment_history"))
print(dataset.columns.get_loc("type_of_credit_accounts"))
print(dataset.columns.get_loc("public_records_and_collections"))
print(dataset.columns.get_loc("purpose_of_loan"))
print(dataset.columns.get_loc("approval_status"))

0
1
2
3
4
5
6
19


In [9]:
# Print all the categorical columns in the dataset
print(dataset.select_dtypes(include=['object']).columns)

Index(['credit_history', 'employment_status', 'collateral', 'payment_history',
       'type_of_credit_accounts', 'public_records_and_collections',
       'purpose_of_loan', 'approval_status'],
      dtype='object')


In [10]:
# Encoding the dependent variable vector

# Import the library for encoding the categorical data
from sklearn.preprocessing import LabelEncoder

# Create an object of the LabelEncoder class
le = LabelEncoder()

# Encoding the dependent variable vector
y = le.fit_transform(y)

In [11]:
# Print first 5 rows with the dependent variable vector after encoding
print(y[:5])

[1 1 1 1 1]


In [12]:
# Split the dataset into training and test sets

# Import the library for splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [13]:
# Print first 5 rows from the X training set
print(X_train[:5])

[[0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 36933 32921
  12 23 5 2 1 12728 4417 33 1673 17013]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 42898 41738
  50 21 3 5 0 10581 1886 7 4918 5022]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 12434 31547
  32 80 0 3 2 11553 16452 33 3848 6464]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 18089 18164
  78 44 1 3 5 4784 12920 59 1886 7582]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 1.0
  0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 15341 47687
  87 62 2 0 3 11877 1632 22 2821 11378]]


In [14]:
# Print first 5 rows from the X test set
print(X_test[:5])

[[0.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 14670 28260
  79 29 4 2 0 13341 1874 22 2942 6405]
 [0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0
  0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 20346 20062
  90 21 1 5 0 19669 2938 59 2848 9107]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 46322 40877
  60 94 4 3 4 1829 2499 0 3514 3353]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 41282 13191
  38 54 5 3 3 15807 5887 92 3152 19206]
 [0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 22875 19554
  38 83 2 2 5 12738 8179 52 2228 17945]]


In [15]:
# Print first 5 rows from the Y training set
print(y_train[:5])

[1 1 0 1 1]


In [16]:
# Print first 5 rows from the Y test set
print(y_test[:5])

[0 1 1 1 1]


In [92]:
from sklearn.preprocessing import StandardScaler

# Create an instance of the StandardScaler class
scaler = StandardScaler()

# Select numerical columns with index 1, 4, 5, 7, 8, 9, 10, 12, 13, 14, 16, 17, and 18
X_train_num = X_train[:, [1, 4, 5, 7, 8, 9, 10, 12, 13, 14, 16, 17, 18]]

# Transform the training set using the fitted scaler for numerical columns with index 1, 4, 5, 7, 8, 9, 10, 12, 13, 14, 16, 17, and 18
X_train_num = X_train_num.assign(scaled=scaler.fit_transform(X_train_num))

# Transform the test set using the fitted scaler for numerical columns with index 1, 4, 5, 7, 8, 9, 10, 12, 13, 14, 16, 17, and 18
X_test_num = X_test[:, [1, 4, 5, 7, 8, 9, 10, 12, 13, 14, 16, 17, 18]]
X_test_num = X_test_num.assign(scaled=scaler.transform(X_test_num))


AttributeError: 'numpy.ndarray' object has no attribute 'assign'